feat: blue green 무중단 배포 스크립트

diff --git a/.github/workflows/backend-prod.yml b/.github/workflows/backend-prod.yml
--- a/.github/workflows/backend-prod.yml
+++ b/.github/workflows/backend-prod.yml
@@ -134,38 +134,42 @@ jobs:
 
             # Update Nginx configuration file on host
             echo "Updating Nginx configuration file on host..."
-            sudo sed -i "s/proxy_pass http:\/\/127.0.0.1:.*;/proxy_pass http:\/\/127.0.0.1:${{ steps.check-port.outputs.next_port }};/" ./nginx.conf
+            sudo sed -i "s/proxy_pass http:\/\/127.0.0.1:.*;/proxy_pass http:\/\/127.0.0.1:${{ steps.check-port.outputs.next_port }};/" ./nginx-conf/default.conf
 
-            # Reload Nginx inside the container
-            echo "Reloading Nginx inside the container..."
-            sudo docker exec $NGINX_CONTAINER_NAME nginx -s reload
+            # Test Nginx configuration
+            echo "Testing Nginx configuration..."
+            sudo docker exec $NGINX_CONTAINER_NAME nginx -t
 
-            echo "Nginx configuration updated and reloaded."
+            # If the configuration test passes, reload Nginx
+            if [ $? -eq 0 ]; then
+              echo "Reloading Nginx inside the container..."
+              sudo docker exec $NGINX_CONTAINER_NAME nginx -s reload
+              echo "Nginx configuration updated and reloaded."
+            else
+              echo "Nginx configuration test failed. Please check the configuration file."
+              sudo docker exec $NGINX_CONTAINER_NAME nginx -t
+              exit 1
+            fi
 
           else
             echo "Nginx container not found. Creating a new Nginx container..."
 
+            # Create Nginx configuration directory
+            mkdir -p ./nginx-conf
+
             # Create a basic Nginx config file with the updated proxy_pass
             echo "
-            worker_processes 1;
-
-            events {
-              worker_connections 1024;
-            }
-
-            http {
-              server {
-                listen 80;
-                location / {
-                  proxy_pass http://127.0.0.1:${{ steps.check-port.outputs.next_port }};
-                }
+            server {
+              listen 80;
+              location / {
+                proxy_pass http://127.0.0.1:${{ steps.check-port.outputs.next_port }};
               }
             }
-            " > ./nginx.conf
+            " > ./nginx-conf/default.conf
 
             # Run a new Nginx container with the updated config
             sudo docker run -d --name $NGINX_CONTAINER_NAME -p 80:80 \
-              -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx
+              -v $(pwd)/nginx-conf:/etc/nginx/conf.d:ro nginx
 
             echo "New Nginx container created and running."
           fi
